#**Tensors in PyTorch**

##Initialising Setup

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [4]:
if torch.cuda.is_available():
  print("GPU: ", torch.cuda.get_device_name(0))
else:
  print("NO GPU")

NO GPU


##Creating a Tensor

In [5]:
#Empty -- allocates memory space for the desired tensor . The output values are the values already present at those memory spaces
a = torch.empty((3,3))
a

tensor([[2.1715e-18, 8.4639e-07, 6.6011e-07],
        [1.6898e-04, 1.0488e-08, 2.0469e+23],
        [1.0368e-11, 2.1747e+23, 4.2467e+21]])

In [6]:
# Checking data type
type(a)

torch.Tensor

In [7]:
# Zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# Random Values
torch.rand(3,3)

tensor([[0.9069, 0.7115, 0.8062],
        [0.7227, 0.3430, 0.5090],
        [0.8042, 0.2532, 0.7486]])

In [10]:
torch.rand(3,3)

tensor([[0.9761, 0.8043, 0.9392],
        [0.2666, 0.0090, 0.8171],
        [0.2246, 0.5099, 0.8762]])

In [11]:
#Seeting seed for reproducibilty
torch.manual_seed(123)
torch.rand(3,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

In [12]:
torch.manual_seed(123)
torch.rand(3,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

In [13]:
# Custom Tensor
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
# arange -- produce sequential data (start,stop,step) where stop isn't included
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [16]:
# linspace -- produce uniform value; separated by equal interval (start,stop,length)
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [17]:
b = torch.linspace(0,10,5)
b

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [18]:
type(b)

torch.Tensor

In [19]:
# eye -- produce identity matrix of desired shape
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
# full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

##Tensor Transformations

In [21]:
b

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [22]:
b.shape

torch.Size([5])

In [23]:
torch.empty_like(b)

tensor([0.0000e+00, 0.0000e+00, 6.8664e-44, 0.0000e+00, 1.2916e-12])

In [24]:
torch.ones_like(b)

tensor([1., 1., 1., 1., 1.])

In [25]:
torch.zeros_like(b)

tensor([0., 0., 0., 0., 0.])

In [26]:
torch.rand_like(b)

tensor([0.7264, 0.3153, 0.6871, 0.0756, 0.1966])

In [96]:
a = torch.tensor([[1,2,3],[4,5,6]])
a.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(a)

tensor([[       197568495616, 7310593858020254331, 3616445622929465956],
        [6067810143103429941, 3904684881392316721, 6499598267820552750]])

In [29]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.rand_like(a) #Error: rand generates floating point no. but here a has integer 'datatype' which aren't able to convert on its own. We will come back to this probolem later.

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

##Tensor Data-types

In [32]:
#finding dtpe
a.dtype

torch.int64

In [33]:
#assign dtype
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
#changing dtype
c=a.to(torch.float32)

In [35]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
c

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [37]:
#Coming back to 'rand_like'
torch.rand_like(a,dtype=torch.float16)

tensor([[0.0469, 0.0552, 0.3115],
        [0.0229, 0.0356, 0.7656]], dtype=torch.float16)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


##Mathematical Operations

### 1. Scalar Operation

In [38]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
a+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [40]:
a-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [41]:
a*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [42]:
a/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [43]:
a**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [44]:
a//2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [45]:
a%2

tensor([[1, 0, 1],
        [0, 1, 0]])

###2. Element Wise Operations

In [46]:
b

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [47]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
a+b #Error: For Element wise operations size of both the operands must be the same

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [49]:
c

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [50]:
a+c

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [51]:
a-c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [52]:
a*c

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [53]:
a/c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [54]:
a//c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [55]:
a%c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [56]:
a**c

tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04]])

###3.Other Operations

In [99]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [97]:
torch.sum(a)

tensor(21)

In [101]:
#sum along column(dim-0)
torch.sum(a,dim=0)

tensor([5, 7, 9])

In [102]:
#sum along rows(dim-1)
torch.sum(a,dim=1)

tensor([ 6, 15])

In [103]:
torch.mean(a) #Error: This is a widely occuring problem. For this just convert the dtype of variable

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [106]:
a = a.to(torch.float16)

In [107]:
torch.mean(a)

tensor(3.5000, dtype=torch.float16)

In [108]:
torch.median(a)

tensor(3., dtype=torch.float16)

In [109]:
torch.max(a)

tensor(6., dtype=torch.float16)

In [110]:
torch.min(a)

tensor(1., dtype=torch.float16)

In [111]:
torch.prod(a)

tensor(720., dtype=torch.float16)

In [112]:
torch.std(a)

tensor(1.8711, dtype=torch.float16)

In [113]:
torch.var(a)

tensor(3.5000, dtype=torch.float16)

In [116]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [119]:
c

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [120]:
a>c

tensor([[False, False, False],
        [False, False, False]])

In [121]:
a<c

tensor([[False, False, False],
        [False, False, False]])

In [122]:
a>=c

tensor([[True, True, True],
        [True, True, True]])

In [123]:
a<=c

tensor([[True, True, True],
        [True, True, True]])

In [124]:
a==c

tensor([[True, True, True],
        [True, True, True]])

In [125]:
a!=c

tensor([[False, False, False],
        [False, False, False]])

In [114]:
# index of max available element
torch.argmax(a)

tensor(5)

In [115]:
# index of min available element
torch.argmin(a)

tensor(0)

In [57]:
# neg
d = torch.neg(a)
d

tensor([[-1, -2, -3],
        [-4, -5, -6]])

In [58]:
# abs
torch.abs(d)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [59]:
d=d+0.2
d

tensor([[-0.8000, -1.8000, -2.8000],
        [-3.8000, -4.8000, -5.8000]])

In [60]:
#round
torch.round(d)

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [61]:
#ceil
torch.ceil(d)

tensor([[-0., -1., -2.],
        [-3., -4., -5.]])

In [62]:
#floor
torch.floor(d)

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [63]:
#clamp -- (var, min, max) -- makes the values to be between min and max. if any value>max => value = max and if any value<min => value = min
torch.clamp(d,min = -4, max = -1)

tensor([[-1.0000, -1.8000, -2.8000],
        [-3.8000, -4.0000, -4.0000]])

In [64]:
#randint -- random integers
e = torch.randint(size=(10,), low = 11, high = 100, dtype = torch.float16)
e

tensor([16., 38., 30., 31., 65., 90., 61., 63., 24., 34.], dtype=torch.float16)

In [65]:
#concat
e=torch.concat((e,torch.tensor([2.71])),dim=0)

In [66]:
e

tensor([16.0000, 38.0000, 30.0000, 31.0000, 65.0000, 90.0000, 61.0000, 63.0000,
        24.0000, 34.0000,  2.7100])

In [67]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [68]:
a= torch.concat((a,torch.tensor([[2.71,0,10]])),dim=0)
a

tensor([[ 1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000],
        [ 2.7100,  0.0000, 10.0000]])

In [71]:
#log
torch.log(a)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918],
        [0.9969,   -inf, 2.3026]])

In [72]:
#exp
torch.exp(a)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.5029e+01, 1.0000e+00, 2.2026e+04]])

In [73]:
#sqrt
torch.sqrt(a)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495],
        [1.6462, 0.0000, 3.1623]])

In [74]:
#sigmoid
torch.sigmoid(a)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975],
        [0.9376, 0.5000, 1.0000]])

In [75]:
#softmax -- dim argument specifies dim along which the prob =1
torch.softmax(a, dim=0)

tensor([[3.7574e-02, 4.7123e-02, 8.9468e-04],
        [7.5468e-01, 9.4650e-01, 1.7970e-02],
        [2.0774e-01, 6.3775e-03, 9.8114e-01]])

In [76]:
#relu
torch.relu(a)

tensor([[ 1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000],
        [ 2.7100,  0.0000, 10.0000]])

In [77]:
#transpose -- (var, dim1, dim2, ..) --need to specify dimensions which needs to be reveresed
torch.transpose(a,1,0)

tensor([[ 1.0000,  4.0000,  2.7100],
        [ 2.0000,  5.0000,  0.0000],
        [ 3.0000,  6.0000, 10.0000]])

In [78]:
#det --- only for square matrices
torch.det(a)

tensor(-38.1300)

In [79]:
#inverse -- only for square matrices
torch.inverse(a)

tensor([[-1.3113,  0.5245,  0.0787],
        [ 0.6226, -0.0490, -0.1574],
        [ 0.3554, -0.1421,  0.0787]])

In [80]:
#Matrix Multiplication
torch.matmul(c,a)

tensor([[ 17.1300,  12.0000,  45.0000],
        [ 40.2600,  33.0000, 102.0000]])

In [81]:
#dot product
torch.dot(a,c) #Error: for dot product, both operands must be in 1D

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [83]:
#flatten
x = a.flatten()
y = c.flatten()
x

tensor([ 1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  2.7100,  0.0000,
        10.0000])

In [84]:
torch.dot(x,y) #Error: For Dot Product, size of both opereands must be the same

RuntimeError: inconsistent tensor size, expected tensor [9] and src [6] to have the same number of elements, but got 9 and 6 elements respectively

In [85]:
y

tensor([1., 2., 3., 4., 5., 6.])

In [94]:
y = torch.concat((y,torch.tensor([7,8,9])),dim=0)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
torch.dot(x,y)

tensor(199.9700)

##Cloning and Inplace Operations

In [2]:
z = torch.tensor([1,2,3,4,5])
z

tensor([1, 2, 3, 4, 5])

In [3]:
# Easiest way of copying is using assignment operator
x = z
x

tensor([1, 2, 3, 4, 5])

In [4]:
#Problem: Assignment operator don't create a new memory location; it just adds a new pointer to exisitng memory location
id(x)

136040081422000

In [5]:
id(z) #As both's id is exactly same

136040081422000

In [6]:
#Problem: So One changing one, other will automatically tend to change
z[0]=11
z

tensor([11,  2,  3,  4,  5])

In [7]:
x

tensor([11,  2,  3,  4,  5])

In [8]:
#Solution: Do Cloning instead
x = z.clone()
x

tensor([11,  2,  3,  4,  5])

In [9]:
id(z)

136040081422000

In [10]:
id(x)

136039729766848

In [11]:
z[0] = 31
z

tensor([31,  2,  3,  4,  5])

In [12]:
x

tensor([11,  2,  3,  4,  5])

In [13]:
#Problem: Using standard operation, z = z+c, creates a new tensor z and do addition and then points the exisiting z pointer to this new tensor. But this approach is inefficient when we are dealing with large chunk of data as we have limited memory in our machines.
#Solution: Instead use inplace operator(_) which modifies the existing tensor. But use it with caution as it can cause problems.
z.add_(x)

tensor([42,  4,  6,  8, 10])

In [14]:
z.relu_()

tensor([42,  4,  6,  8, 10])

In [15]:
z.dot_(c) #Error: As dot operator outputs a single value, so it don't make sense to modify whole tensor.

AttributeError: 'Tensor' object has no attribute 'dot_'

In [16]:
z


tensor([42,  4,  6,  8, 10])

##Using GPU for Operations

In [2]:
#Ensure GPU is avaialable
print(torch.cuda.is_available())

True


In [4]:
dev = torch.device('cuda')

In [6]:
# Making new tensor on GPU
o = torch.tensor([[1,2,3],[-4,-5,-6]],device = dev)
o

tensor([[ 1,  2,  3],
        [-4, -5, -6]], device='cuda:0')

In [12]:
# Changing CPU tensor to GPU
p = torch.tensor([[1,2,3],[4,5,6]])
p = p.to(dev)
p

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [20]:
import time

In [21]:
# CPU opeartion Time
mat1 = torch.rand((10000,10000))
mat2 = torch.rand((10000,10000))
start_time= time.time()
torch.matmul(mat1,mat2)
t_time = time.time() - start_time
t_time

27.62849235534668

In [22]:
# GPU opeartion Time
mat1 = mat1.to(dev)
mat2 = mat2.to(dev)
start_time= time.time()
torch.matmul(mat1,mat2)
torch.cuda.synchronize() #Waits for all GPU operations to end
t_time = time.time() - start_time
t_time

0.7029993534088135

##Playing with Dimensions

In [25]:
a = mat1
a.shape

torch.Size([10000, 10000])

In [29]:
#reshape
a.reshape(10,1000,100).shape #Error: The size should remain the same

RuntimeError: shape '[10, 1000, 100]' is invalid for input of size 100000000

In [31]:
a = a.reshape(10,1000,10000)
a.shape

torch.Size([10, 1000, 10000])

In [30]:
#flatten
a.flatten().shape

torch.Size([100000000])

In [33]:
#permute -- Can shift dimensions using indices
a.permute(1,0,2).shape

torch.Size([1000, 10, 10000])

In [34]:
#unsqueeze -- Add a new dimension at specified index. Widely used in Vision related tasks
a = a.unsqueeze(0)
a.shape

torch.Size([1, 10, 1000, 10000])

In [35]:
#squeeze -- Remove existing dimension from specified index
a.squeeze(0).shape

torch.Size([10, 1000, 10000])

## PyTorch and Numpy

In [37]:
a.shape

torch.Size([10, 1000, 10000])

In [38]:
type(a)

torch.Tensor

In [41]:
# Torch_Tensor to Numpy
type(a.numpy()) #Error: For conversion, you need tensors to be in CPU.

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [42]:
# GPU --> CPU
a = a.to('cpu')
a

tensor([[[0.8443, 0.0210, 0.4943,  ..., 0.1562, 0.8362, 0.7888],
         [0.7815, 0.7203, 0.7285,  ..., 0.7477, 0.1447, 0.0877],
         [0.6081, 0.4028, 0.3184,  ..., 0.3413, 0.1725, 0.5196],
         ...,
         [0.5366, 0.6860, 0.3255,  ..., 0.9613, 0.6529, 0.8409],
         [0.5671, 0.5043, 0.0370,  ..., 0.5835, 0.7257, 0.6190],
         [0.6429, 0.2467, 0.9081,  ..., 0.7269, 0.6652, 0.9881]],

        [[0.0314, 0.4365, 0.5876,  ..., 0.0646, 0.9297, 0.5409],
         [0.2104, 0.4493, 0.8619,  ..., 0.7339, 0.2441, 0.3323],
         [0.9209, 0.8770, 0.4884,  ..., 0.9524, 0.6453, 0.3374],
         ...,
         [0.9601, 0.3400, 0.4287,  ..., 0.7271, 0.7799, 0.3119],
         [0.1599, 0.8002, 0.3220,  ..., 0.1299, 0.9989, 0.7989],
         [0.2473, 0.5234, 0.0161,  ..., 0.5942, 0.6705, 0.2981]],

        [[0.2203, 0.1788, 0.4074,  ..., 0.9832, 0.9170, 0.5808],
         [0.4380, 0.5840, 0.6389,  ..., 0.1317, 0.5325, 0.6781],
         [0.9848, 0.1988, 0.6260,  ..., 0.8730, 0.6081, 0.

In [45]:
a = a.numpy()
type(a)

numpy.ndarray

In [46]:
# From numpy to Torch_tensor
a = torch.from_numpy(a)
type(a)

torch.Tensor