# 1.Obtaining the Dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
76     8610629         B       13.530         10.94           87.91   
526   91813701         B       13.460         18.75           87.44   
0       842302         M       17.990         10.38          122.80   
126     866083         M       13.610         24.69           87.76   
55    85759902         B       11.520         18.75           73.34   
53      857392         M       18.220         18.70          120.30   
534     919537         B       10.960         17.62           70.79   
358    9010333         B        8.878         15.49           56.74   
21     8510824         B        9.504         12.44           60.34   
461  911296202         M       27.420         26.27          186.90   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
76       559.2          0.12910           0.10470         0.06877   
526      551.1          0.10750           0.11380         0.04201   
0       1001.0          0.11840           0.27760         0.30010   
126      572.6          0.09258           0.07862         0.05285   
55       409.0          0.09524           0.05473         0.03036   
53      1033.0          0.11480           0.14850         0.17720   
534      365.6          0.09687           0.09752         0.05263   
358      241.0          0.08293           0.07698         0.04721   
21       273.9          0.10240           0.06492         0.02956   
461     2501.0          0.10840           0.19880         0.36350   

     concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
76               0.06556  ...          12.49            91.36       605.5   
526              0.03152  ...          25.16           101.90       719.8   
0                0.14710  ...          17.33           184.60      2019.0   
126              0.03085  ...          35.64           113.20       848.7   
55               0.02278  ...          22.47            81.81       506.2   
53               0.10600  ...          24.13           135.10      1321.0   
534              0.02788  ...          26.51            76.43       407.5   
358              0.02381  ...          17.70            65.27       302.0   
21               0.02076  ...          15.66            65.13       314.9   
461              0.16890  ...          31.37           251.20      4254.0   

     smoothness_worst  compactness_worst  concavity_worst  \
76             0.1451             0.1379          0.08539   
526            0.1624             0.3124          0.26540   
0              0.1622             0.6656          0.71190   
126            0.1471             0.2884          0.37960   
55             0.1249             0.0872          0.09076   
53             0.1280             0.2297          0.26230   
534            0.1428             0.2510          0.21230   
358            0.1015             0.1248          0.09441   
21             0.1324             0.1148          0.08867   
461            0.1357             0.4256          0.68330   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
76                0.07407          0.2710                  0.07191   
526               0.14270          0.3518                  0.08665   
0                 0.26540          0.4601                  0.11890   
126               0.13290          0.3470                  0.07900   
55                0.06316          0.3306                  0.07036   
53                0.13250          0.3021                  0.07987   
534               0.09861          0.2289                  0.08278   
358               0.04762          0.2434                  0.07431   
21                0.06227          0.2450                  0.07773   
461               0.26250          0.2641                  0.07427   

     Unnamed: 32  
76           NaN  
526          NaN  
0            NaN  
126          NaN  
55           NaN  
53           NaN  
534          NaN  
358          NaN  
21      

# 2.Basic PreProcessing

In [ ]:
df.shape

(569, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace=True)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
516        18.31         20.58          120.80     1052.0          0.10680   
250        20.94         23.56          138.90     1364.0          0.10070   
311        14.61         15.69           92.68      664.9          0.07618   
121        18.66         17.12          121.40     1077.0          0.10540   
74         12.31         16.52           79.19      470.9          0.09172   
..           ...           ...             ...        ...              ...   
555        10.29         27.61           65.67      321.4          0.09030   
316        12.18         14.08           77.25      461.4          0.07734   
508        16.30         15.70          104.70      819.8          0.09427   
390        10.26         12.22           65.75      321.6          0.09996   
547        10.26         16.58           65.85      320.8          0.08877   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
516           0.12480         0.15690             0.094510         0.1860   
250           0.16060         0.27120             0.131000         0.2205   
311           0.03515         0.01447             0.018770         0.1632   
121           0.11000         0.14570             0.086650         0.1966   
74            0.06829         0.03372             0.022720         0.1720   
..                ...             ...                  ...            ...   
555           0.07658         0.05999             0.027380         0.1593   
316           0.03212         0.01123             0.005051         0.1673   
508           0.06712         0.05526             0.045630         0.1711   
390           0.07542         0.01923             0.019680         0.1800   
547           0.08066         0.04358             0.024380         0.1669   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
516                 0.05941  ...         21.86          26.20   
250                 0.05898  ...         25.58          27.00   
311                 0.05255  ...         16.46          21.75   
121                 0.06213  ...         22.25          24.90   
74                  0.05914  ...         14.11          23.21   
..                      ...  ...           ...            ...   
555                 0.06127  ...         10.84          34.91   
316                 0.05649  ...         12.85          16.47   
508                 0.05657  ...         17.32          17.76   
390                 0.06569  ...         11.38          15.65   
547                 0.06714  ...         10.83          22.04   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
516           142.20      1493.0            0.1492            0.25360   
250           165.30      2010.0            0.1211            0.31720   
311           103.70       840.8            0.1011            0.07087   
121           145.40      1549.0            0.1503            0.22910   
74             89.71       611.1            0.1176            0.18430   
..               ...         ...               ...                ...   
555            69.57       357.6            0.1384            0.17100   
316            81.60       513.1            0.1001            0.05332   
508           109.80       928.2            0.1354            0.13610   
390            73.23       394.5            0.1343            0.16500   
547            71.08       357.4            0.1461            0.22460   

     concavity_worst  concave points_worst  symmetry_worst  \
516          0.37590               0.15100          0.3074   
250          0.69910               0.21050          0.3126   
311          0.04746               0.05813          0.2530   
121          0.32720               0.16740          0.2894   
74           0.17030               0.08660          0.2618   
..               ...                   ...             ...   
555          0.20000               0.09127         

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X_test,X_test.shape)

[[ 3.71901664e-02 -1.49858252e+00 -3.97143647e-02 ... -8.03819078e-01
  -1.31452258e+00 -7.54231982e-01]
 [-2.84338740e-01 -9.97084587e-04 -2.66795280e-01 ... -2.04935982e-01
   1.12523592e+00  4.58799626e-01]
 [-3.58318842e-01 -3.89860074e-01 -4.12687556e-01 ... -1.14763352e+00
  -1.20851703e+00 -1.37035653e+00]
 ...
 [-2.47348689e-01 -8.78253471e-01 -1.55933635e-01 ...  1.30464787e+00
   3.92982197e-01  3.30298896e+00]
 [-3.12792626e-01  2.21413316e+00 -3.50044544e-01 ... -7.12809374e-01
  -8.70930128e-01 -6.61638595e-01]
 [ 2.19968547e+00 -4.87075821e-01  2.05676588e+00 ...  1.05410706e+00
  -6.45872191e-01 -1.09723516e+00]] (114, 30)


In [ ]:
y_train

516    M
250    M
311    B
121    M
74     B
      ..
555    B
316    B
508    B
390    B
547    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
print(y_test,y_test.shape,type(y_test))

[0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0 1 0 0 0
 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1
 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 1 0
 1 0 1] (114,) <class 'numpy.ndarray'>


In [ ]:
import torch
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)
print(y_test,y_test.shape,type(y_test),y_test.dtype)

tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1]) torch.Size([114]) <class 'torch.Tensor'> torch.int64


#3.Training Process

In [48]:
class onelayernn:

  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.rand(1,dtype=torch.float64, requires_grad=True)

  def forward_pass(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss(self,y_pred):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon) #clamping to avoid log(0) after sigmoid operation
    loss = -((y_train * torch.log(y_pred)) + ((1-y_train)*torch.log(1-y_pred))).mean()
    return loss

In [83]:
epochs = 250
learning_rate = 0.1

In [84]:
#A. Creating Model
model = onelayernn(X_train)

for epoch in range(epochs):
  #B. Forward Pass
  y_pred = model.forward_pass(X_train)
  #C.Loss Calculation
  loss = model.loss(y_pred)
  print(f"Loss for Epoch {epoch+1}: ",loss.item())
  loss.backward()
  #D.Parameter Updates using Backpropogation
  with torch.no_grad():
    model.weights -= model.weights.grad * learning_rate
    model.bias -= model.bias.grad * learning_rate

  model.weights.grad.zero_()
  model.bias.grad.zero_()


Loss for Epoch 1:  3.4108523961816246
Loss for Epoch 2:  3.2759879397166562
Loss for Epoch 3:  3.1387314331640286
Loss for Epoch 4:  2.9926829140004676
Loss for Epoch 5:  2.843606568693616
Loss for Epoch 6:  2.692913309804713
Loss for Epoch 7:  2.5399861771025876
Loss for Epoch 8:  2.3846678691867083
Loss for Epoch 9:  2.229342961168887
Loss for Epoch 10:  2.0753651752842517
Loss for Epoch 11:  1.9282384215706945
Loss for Epoch 12:  1.7889690217199221
Loss for Epoch 13:  1.6585803538086354
Loss for Epoch 14:  1.5349088263127182
Loss for Epoch 15:  1.4131970209401594
Loss for Epoch 16:  1.3043604734703989
Loss for Epoch 17:  1.209171016814005
Loss for Epoch 18:  1.1279644539189617
Loss for Epoch 19:  1.0604858098702623
Loss for Epoch 20:  1.0058193279288186
Loss for Epoch 21:  0.9624406862200368
Loss for Epoch 22:  0.9284093045021528
Loss for Epoch 23:  0.9016650941757592
Loss for Epoch 24:  0.8803185244948892
Loss for Epoch 25:  0.8628294157247934
Loss for Epoch 26:  0.8480533947713069

In [85]:
model.bias

tensor([-0.5890], dtype=torch.float64, requires_grad=True)

In [86]:
model.weights

tensor([[ 0.4599],
        [ 0.1564],
        [ 0.0798],
        [-0.3007],
        [ 0.1695],
        [-0.3766],
        [-0.3096],
        [ 0.0186],
        [ 0.0704],
        [ 0.1224],
        [-0.4590],
        [ 0.0710],
        [ 0.1625],
        [ 0.1986],
        [ 0.0551],
        [ 0.1543],
        [ 0.1265],
        [ 0.0292],
        [ 0.1002],
        [-0.3256],
        [ 0.2121],
        [-0.1959],
        [-0.3021],
        [ 0.2868],
        [-0.1100],
        [-0.0022],
        [ 0.1205],
        [-0.0730],
        [-0.1204],
        [ 0.3606]], dtype=torch.float64, requires_grad=True)

#4.Evaluation

In [88]:
with torch.no_grad():
  y_test_pred = model.forward_pass(X_test)
  y_test_pred = (y_test_pred>0.5).float()
  accuracy = (y_test_pred == y_test).float().mean()
  print("Accuracy: ", accuracy.item())

Accuracy:  0.5664820075035095
